### ISSUE TITLE
Doesn't update from "in main menu"

### ISSUE THREAD

**Issue by GustavoGarufi** [AipNooBest/wow-discord-rpc#4]
I'm trying to run this plugin on WotLK, 3.3.5a on [Warmane](https://www.warmane.com/download) (which is a private server), and it seems to initialize correctly. The problem is that it doesn't update from "in main menu" like at all. 

![image](https://github.com/AipNooBest/wow-discord-rpc/assets/21698991/90026a62-49ea-4a61-90a6-68bb09fc567a)

I'm not exactly sure what is causing the issue cause I do see the colors in the corner of my screen.

![image-colors-1](https://github.com/AipNooBest/wow-discord-rpc/assets/21698991/8ecb7c14-9e93-439d-a3d2-3d000fa37e7b)
![image-colors-2](https://github.com/AipNooBest/wow-discord-rpc/assets/21698991/2afc5cbd-262e-4548-97e6-c53a13ed5b4f)

Any ideas what's going on here? I don't know any lua or python as I mostly do JS/PHP so I'm drawing blanks here.

**Comment by AipNooBest** [comment]
Hello, could you please provide a `log.txt` file with `logging.DEBUG` option [here](https://github.com/AipNooBest/wow-discord-rpc/blob/caeaad8f39d53139c64cd37b63a7db6c5ad2fa25/script/WoWPresence.py#LL17C91-L17C91)
Also, at what resolution do you play? I can try to replicate this, my guess is that pixels are merging with each others and there's a decoding issue because of that

**Comment by GustavoGarufi** [comment]
> Hello, could you please provide a `log.txt` file with `logging.DEBUG` option [here](https://github.com/AipNooBest/wow-discord-rpc/blob/caeaad8f39d53139c64cd37b63a7db6c5ad2fa25/script/WoWPresence.py#LL17C91-L17C91) Also, at what resolution do you play? I can try to replicate this, my guess is that pixels are merging with each others and there's a decoding issue because of that

log.txt on default would pretty much gives me this

```
INFO:root:Not connected to Discord, connecting...
INFO:rpc:connected via ID 827272838771507210
INFO:root:Setting activity: In main menu
INFO:root:Setting activity: In main menu
INFO:root:Setting activity: In main menu
INFO:root:Setting activity: In main menu
INFO:root:Setting activity: In main menu
INFO:root:Setting activity: In main menu
INFO:root:Setting activity: In main menu
INFO:root:Setting activity: In main menu
INFO:root:Setting activity: In main menu
INFO:root:Setting activity: In main menu
INFO:root:Setting activity: In main menu
INFO:root:Setting activity: In main menu
INFO:root:Setting activity: In main menu
INFO:root:Setting activity: In main menu
INFO:root:Setting activity: In main menu
INFO:root:Setting activity: In main menu
INFO:root:Setting activity: In main menu
INFO:root:Setting activity: In main menu
INFO:root:Setting activity: In main menu
INFO:root:Setting activity: In main menu
INFO:root:Setting activity: In main menu
INFO:root:Setting activity: In main menu
INFO:root:WoW no longer exists, terminating...
WARNING:rpc:closing connection
```
If I add logging.debug I get
```
DEBUG:root:Window rectangle: (0, 0, 1920, 2); Iteration 0
DEBUG:root:Pixel at position 0,0: (34, 67, 78)
DEBUG:root:Window border height: 31
DEBUG:root:Window rectangle: (0, 31, 1920, 33); Iteration 1
DEBUG:root:Pixel at position 0,0: (36, 69, 83)
DEBUG:root:Window rectangle: (8, 31, 1920, 33); Iteration 2
DEBUG:root:Pixel at position 0,0: (35, 68, 81)
INFO:root:Not connected to Discord, connecting...
DEBUG:rpc:sending {'v': 1, 'client_id': '827272838771507210'}
DEBUG:rpc:received {'cmd': 'DISPATCH', 'data': {'v': 1, 'config': {'cdn_host': 'cdn.discordapp.com', 'api_endpoint': '//discord.com/api', 'environment': 'production'}, 'user': {'id': '182282771597623296', 'username': 'Beefy', 'discriminator': '5528', 'avatar': '32c3be648d2b73dbeabc70f71e3a9ba1', 'avatar_decoration': 'v3_a_88765df09a036906b376704bd8dc27ba', 'bot': False, 'flags': 48, 'premium_type': 2}}, 'evt': 'READY', 'nonce': None}
INFO:rpc:connected via ID 827272838771507210
INFO:root:Setting activity: In main menu
DEBUG:rpc:sending {'cmd': 'SET_ACTIVITY', 'args': {'pid': 19744, 'activity': {'details': 'In main menu', 'timestamps': {'start': 1685007447}, 'assets': {'large_image': 'wow-icon'}}}, 'nonce': '545a0a21-2617-429f-9e6f-8545db1e5606'}
DEBUG:root:Window rectangle: (0, 0, 1920, 2); Iteration 0
DEBUG:root:Pixel at position 0,0: (74, 44, 24)
DEBUG:root:Window border height: 31
DEBUG:root:Window rectangle: (0, 31, 1920, 33); Iteration 1
DEBUG:root:Pixel at position 0,0: (122, 67, 28)
DEBUG:root:Window rectangle: (8, 31, 1920, 33); Iteration 2
DEBUG:root:Pixel at position 0,0: (32, 96, 93)
INFO:root:Setting activity: In main menu
DEBUG:rpc:sending {'cmd': 'SET_ACTIVITY', 'args': {'pid': 19744, 'activity': {'details': 'In main menu', 'timestamps': {'start': 1685007447}, 'assets': {'large_image': 'wow-icon'}}}, 'nonce': '51ba1b0f-e791-4131-bde8-7347fb54737c'}
DEBUG:root:Window rectangle: (0, 0, 1920, 2); Iteration 0
DEBUG:root:Pixel at position 0,0: (0, 0, 0)
DEBUG:root:Window border height: 31
DEBUG:root:Window rectangle: (0, 31, 1920, 33); Iteration 1
DEBUG:root:Pixel at position 0,0: (0, 0, 0)
DEBUG:root:Window rectangle: (8, 31, 1920, 33); Iteration 2
DEBUG:root:Pixel at position 0,0: (0, 0, 0)
INFO:root:Setting activity: In main menu
DEBUG:rpc:sending {'cmd': 'SET_ACTIVITY', 'args': {'pid': 19744, 'activity': {'details': 'In main menu', 'timestamps': {'start': 1685007447}, 'assets': {'large_image': 'wow-icon'}}}, 'nonce': '63048bc4-89ec-4a3e-b9b9-5b8b9b0ec777'}
DEBUG:root:Window rectangle: (0, 0, 1920, 2); Iteration 0
DEBUG:root:Pixel at position 0,0: (32, 29, 29)
DEBUG:root:Window border height: 31
DEBUG:root:Window rectangle: (0, 31, 1920, 33); Iteration 1
DEBUG:root:Pixel at position 0,0: (34, 33, 33)
DEBUG:root:Window rectangle: (8, 31, 1920, 33); Iteration 2
DEBUG:root:Pixel at position 0,0: (32, 96, 93)
INFO:root:Setting activity: In main menu
DEBUG:rpc:sending {'cmd': 'SET_ACTIVITY', 'args': {'pid': 19744, 'activity': {'details': 'In main menu', 'timestamps': {'start': 1685007447}, 'assets': {'large_image': 'wow-icon'}}}, 'nonce': 'f6ca7a76-0acd-4fa4-b8ea-196a6bb98e9a'}
DEBUG:root:Window rectangle: (0, 0, 1920, 2); Iteration 0
DEBUG:root:Pixel at position 0,0: (74, 53, 56)
DEBUG:root:Window border height: 31
DEBUG:root:Window rectangle: (0, 31, 1920, 33); Iteration 1
DEBUG:root:Pixel at position 0,0: (185, 128, 126)
DEBUG:root:Window rectangle: (8, 31, 1920, 33); Iteration 2
DEBUG:root:Pixel at position 0,0: (32, 96, 93)
INFO:root:Setting activity: In main menu
DEBUG:rpc:sending {'cmd': 'SET_ACTIVITY', 'args': {'pid': 19744, 'activity': {'details': 'In main menu', 'timestamps': {'start': 1685007447}, 'assets': {'large_image': 'wow-icon'}}}, 'nonce': 'a323d8b4-8906-4e84-b003-d81316135140'}
DEBUG:root:Window rectangle: (0, 0, 1920, 2); Iteration 0
DEBUG:root:Pixel at position 0,0: (145, 111, 104)
DEBUG:root:Window border height: 31
DEBUG:root:Window rectangle: (0, 31, 1920, 33); Iteration 1
DEBUG:root:Pixel at position 0,0: (143, 113, 113)
DEBUG:root:Window rectangle: (8, 31, 1920, 33); Iteration 2
DEBUG:root:Pixel at position 0,0: (32, 96, 93)
INFO:root:Setting activity: In main menu
DEBUG:rpc:sending {'cmd': 'SET_ACTIVITY', 'args': {'pid': 19744, 'activity': {'details': 'In main menu', 'timestamps': {'start': 1685007447}, 'assets': {'large_image': 'wow-icon'}}}, 'nonce': '4a533389-b5ab-4a4d-b803-0da6f537ec11'}
DEBUG:root:Window rectangle: (0, 0, 1920, 2); Iteration 0
DEBUG:root:Pixel at position 0,0: (81, 44, 21)
DEBUG:root:Window border height: 31
DEBUG:root:Window rectangle: (0, 31, 1920, 33); Iteration 1
DEBUG:root:Pixel at position 0,0: (84, 64, 84)
DEBUG:root:Window rectangle: (8, 31, 1920, 33); Iteration 2
DEBUG:root:Pixel at position 0,0: (32, 96, 93)
INFO:root:Setting activity: In main menu
DEBUG:rpc:sending {'cmd': 'SET_ACTIVITY', 'args': {'pid': 19744, 'activity': {'details': 'In main menu', 'timestamps': {'start': 1685007447}, 'assets': {'large_image': 'wow-icon'}}}, 'nonce': 'ee01aedb-fe9b-4878-a6aa-322f798b96a6'}
DEBUG:root:Window rectangle: (0, 0, 1920, 2); Iteration 0
DEBUG:root:Pixel at position 0,0: (95, 72, 86)
DEBUG:root:Window border height: 31
DEBUG:root:Window rectangle: (0, 31, 1920, 33); Iteration 1
DEBUG:root:Pixel at position 0,0: (93, 70, 87)
DEBUG:root:Window rectangle: (8, 31, 1920, 33); Iteration 2
DEBUG:root:Pixel at position 0,0: (32, 96, 93)
INFO:root:Setting activity: In main menu
DEBUG:rpc:sending {'cmd': 'SET_ACTIVITY', 'args': {'pid': 19744, 'activity': {'details': 'In main menu', 'timestamps': {'start': 1685007447}, 'assets': {'large_image': 'wow-icon'}}}, 'nonce': 'b18edfc7-fe1b-484a-bf4c-2816d5b4d01b'}
DEBUG:root:Window rectangle: (0, 0, 1920, 2); Iteration 0
DEBUG:root:Pixel at position 0,0: (52, 48, 37)
DEBUG:root:Window border height: 31
DEBUG:root:Window rectangle: (0, 31, 1920, 33); Iteration 1
DEBUG:root:Pixel at position 0,0: (88, 85, 60)
DEBUG:root:Window rectangle: (8, 31, 1920, 33); Iteration 2
DEBUG:root:Pixel at position 0,0: (32, 96, 93)
INFO:root:Setting activity: In main menu
DEBUG:rpc:sending {'cmd': 'SET_ACTIVITY', 'args': {'pid': 19744, 'activity': {'details': 'In main menu', 'timestamps': {'start': 1685007447}, 'assets': {'large_image': 'wow-icon'}}}, 'nonce': 'a13dc2ba-c578-4ddd-aaab-ad5730c878a5'}
DEBUG:root:Window rectangle: (0, 0, 1920, 2); Iteration 0
DEBUG:root:Pixel at position 0,0: (104, 77, 86)
DEBUG:root:Window border height: 31
DEBUG:root:Window rectangle: (0, 31, 1920, 33); Iteration 1
DEBUG:root:Pixel at position 0,0: (45, 29, 24)
DEBUG:root:Window rectangle: (8, 31, 1920, 33); Iteration 2
DEBUG:root:Pixel at position 0,0: (32, 96, 93)
INFO:root:Setting activity: In main menu
DEBUG:rpc:sending {'cmd': 'SET_ACTIVITY', 'args': {'pid': 19744, 'activity': {'details': 'In main menu', 'timestamps': {'start': 1685007447}, 'assets': {'large_image': 'wow-icon'}}}, 'nonce': '40c90534-e02a-4bf3-976b-6e997b4a0b15'}
DEBUG:root:Window rectangle: (0, 0, 1920, 2); Iteration 0
DEBUG:root:Pixel at position 0,0: (35, 36, 20)
DEBUG:root:Window border height: 31
DEBUG:root:Window rectangle: (0, 31, 1920, 33); Iteration 1
DEBUG:root:Pixel at position 0,0: (46, 50, 13)
DEBUG:root:Window rectangle: (8, 31, 1920, 33); Iteration 2
DEBUG:root:Pixel at position 0,0: (32, 96, 93)
INFO:root:Setting activity: In main menu
DEBUG:rpc:sending {'cmd': 'SET_ACTIVITY', 'args': {'pid': 19744, 'activity': {'details': 'In main menu', 'timestamps': {'start': 1685007447}, 'assets': {'large_image': 'wow-icon'}}}, 'nonce': 'e3c2a940-54d2-4bbe-bf43-543e0a6c5931'}
INFO:root:WoW no longer exists, terminating...
WARNING:rpc:closing connection
DEBUG:rpc:sending {}
```

I'm running at 1920x1080 (wide), Windowed Mode Maximized at 240Hz. Seems to have worked in Mist of Pandaria though same settings.

**Comment by AipNooBest** [comment]
Ok, looking at the screenshots and log, it seems that 1x1 pixels for addon is too small, maybe 3.3.5 can't handle it, but in newer patches it has been fixed (judging by the fact it works in Pandaria for you). You can try to change width and height of pixels [here](https://github.com/AipNooBest/wow-discord-rpc/blob/caeaad8f39d53139c64cd37b63a7db6c5ad2fa25/IPC.lua#LL7C16-L7C16), it should work. Yeah, it will look a bit ugly, but for now that's the only fix. Tell me if it works, I can't test it on my client now, unfortunately

**Comment by GustavoGarufi** [comment]
Cool Idea, I tried checking with different sizes and it didn't work, and when I say different sizes I mean everything from 2 to like 24, check this out:
![image](https://github.com/AipNooBest/wow-discord-rpc/assets/21698991/eee8e202-65d5-4468-9a65-5a9436f750e4)

here's the log.txt with debug mode enabled while running 24x24 pixels:

`DEBUG:root:Window rectangle: (0, 0, 1920, 2); Iteration 0
DEBUG:root:Pixel at position 0,0: (31, 31, 31)
DEBUG:root:Window border height: 31
DEBUG:root:Window rectangle: (0, 31, 1920, 33); Iteration 1
DEBUG:root:Pixel at position 0,0: (0, 120, 212)
DEBUG:root:Window rectangle: (8, 31, 1920, 33); Iteration 2
DEBUG:root:Pixel at position 0,0: (24, 24, 24)
INFO:root:Not connected to Discord, connecting...
DEBUG:rpc:sending {'v': 1, 'client_id': '827272838771507210'}
DEBUG:rpc:received {'cmd': 'DISPATCH', 'data': {'v': 1, 'config': {'cdn_host': 'cdn.discordapp.com', 'api_endpoint': '//discord.com/api', 'environment': 'production'}, 'user': {'id': '182282771597623296', 'username': 'Beefy', 'discriminator': '5528', 'avatar': '32c3be648d2b73dbeabc70f71e3a9ba1', 'avatar_decoration': 'v3_a_88765df09a036906b376704bd8dc27ba', 'bot': False, 'flags': 48, 'premium_type': 2}}, 'evt': 'READY', 'nonce': None}
INFO:rpc:connected via ID 827272838771507210
INFO:root:Setting activity: In main menu
DEBUG:rpc:sending {'cmd': 'SET_ACTIVITY', 'args': {'pid': 3636, 'activity': {'details': 'In main menu', 'timestamps': {'start': 1685012282}, 'assets': {'large_image': 'wow-icon'}}}, 'nonce': 'bb0d060c-ddb7-4864-a47b-7de4616cbe58'}
DEBUG:root:Window rectangle: (0, 0, 1920, 2); Iteration 0
DEBUG:root:Pixel at position 0,0: (36, 70, 82)
DEBUG:root:Window border height: 31
DEBUG:root:Window rectangle: (0, 31, 1920, 33); Iteration 1
DEBUG:root:Pixel at position 0,0: (39, 72, 86)
DEBUG:root:Window rectangle: (8, 31, 1920, 33); Iteration 2
DEBUG:root:Pixel at position 0,0: (41, 74, 89)
INFO:root:Setting activity: In main menu
DEBUG:rpc:sending {'cmd': 'SET_ACTIVITY', 'args': {'pid': 3636, 'activity': {'details': 'In main menu', 'timestamps': {'start': 1685012282}, 'assets': {'large_image': 'wow-icon'}}}, 'nonce': '2e0af336-2dae-4f66-a4c1-9ec76bb733e6'}
DEBUG:root:Window rectangle: (0, 0, 1920, 2); Iteration 0
DEBUG:root:Pixel at position 0,0: (0, 0, 0)
DEBUG:root:Window border height: 31
DEBUG:root:Window rectangle: (0, 31, 1920, 33); Iteration 1
DEBUG:root:Pixel at position 0,0: (0, 0, 0)
DEBUG:root:Window rectangle: (8, 31, 1920, 33); Iteration 2
DEBUG:root:Pixel at position 0,0: (0, 0, 0)
INFO:root:Setting activity: In main menu
DEBUG:rpc:sending {'cmd': 'SET_ACTIVITY', 'args': {'pid': 3636, 'activity': {'details': 'In main menu', 'timestamps': {'start': 1685012282}, 'assets': {'large_image': 'wow-icon'}}}, 'nonce': 'eb558511-8db1-472f-8a87-f78435ba6c16'}
DEBUG:root:Window rectangle: (0, 0, 1920, 2); Iteration 0
DEBUG:root:Pixel at position 0,0: (74, 52, 71)
DEBUG:root:Window border height: 31
DEBUG:root:Window rectangle: (0, 31, 1920, 33); Iteration 1
DEBUG:root:Pixel at position 0,0: (71, 50, 73)
DEBUG:root:Window rectangle: (8, 31, 1920, 33); Iteration 2
DEBUG:root:Pixel at position 0,0: (32, 96, 93)
INFO:root:Setting activity: In main menu
DEBUG:rpc:sending {'cmd': 'SET_ACTIVITY', 'args': {'pid': 3636, 'activity': {'details': 'In main menu', 'timestamps': {'start': 1685012282}, 'assets': {'large_image': 'wow-icon'}}}, 'nonce': 'c714868a-153f-49f7-929b-edb6dd82563b'}
DEBUG:root:Window rectangle: (0, 0, 1920, 2); Iteration 0
DEBUG:root:Pixel at position 0,0: (32, 32, 21)
DEBUG:root:Window border height: 31
DEBUG:root:Window rectangle: (0, 31, 1920, 33); Iteration 1
DEBUG:root:Pixel at position 0,0: (29, 29, 10)
DEBUG:root:Window rectangle: (8, 31, 1920, 33); Iteration 2
DEBUG:root:Pixel at position 0,0: (32, 96, 93)
INFO:root:Setting activity: In main menu
DEBUG:rpc:sending {'cmd': 'SET_ACTIVITY', 'args': {'pid': 3636, 'activity': {'details': 'In main menu', 'timestamps': {'start': 1685012282}, 'assets': {'large_image': 'wow-icon'}}}, 'nonce': '997ddeb1-dfc9-456e-b13d-dc01a26b5e5f'}
DEBUG:root:Window rectangle: (0, 0, 1920, 2); Iteration 0
DEBUG:root:Pixel at position 0,0: (42, 27, 22)
DEBUG:root:Window border height: 31
DEBUG:root:Window rectangle: (0, 31, 1920, 33); Iteration 1
DEBUG:root:Pixel at position 0,0: (177, 131, 159)
DEBUG:root:Window rectangle: (8, 31, 1920, 33); Iteration 2
DEBUG:root:Pixel at position 0,0: (32, 96, 93)
INFO:root:Setting activity: In main menu
DEBUG:rpc:sending {'cmd': 'SET_ACTIVITY', 'args': {'pid': 3636, 'activity': {'details': 'In main menu', 'timestamps': {'start': 1685012282}, 'assets': {'large_image': 'wow-icon'}}}, 'nonce': '3456ea00-8b6e-44ce-91cb-353b1e55ffff'}
DEBUG:root:Window rectangle: (0, 0, 1920, 2); Iteration 0
DEBUG:root:Pixel at position 0,0: (66, 35, 63)
DEBUG:root:Window border height: 31
DEBUG:root:Window rectangle: (0, 31, 1920, 33); Iteration 1
DEBUG:root:Pixel at position 0,0: (88, 45, 87)
DEBUG:root:Window rectangle: (8, 31, 1920, 33); Iteration 2
DEBUG:root:Pixel at position 0,0: (32, 96, 93)
INFO:root:Setting activity: In main menu
DEBUG:rpc:sending {'cmd': 'SET_ACTIVITY', 'args': {'pid': 3636, 'activity': {'details': 'In main menu', 'timestamps': {'start': 1685012282}, 'assets': {'large_image': 'wow-icon'}}}, 'nonce': '0ea23d6d-7e29-489b-be95-b40a861e8804'}
DEBUG:root:Window rectangle: (0, 0, 1920, 2); Iteration 0
DEBUG:root:Pixel at position 0,0: (44, 47, 23)
DEBUG:root:Window border height: 31
DEBUG:root:Window rectangle: (0, 31, 1920, 33); Iteration 1
DEBUG:root:Pixel at position 0,0: (22, 25, 9)
DEBUG:root:Window rectangle: (8, 31, 1920, 33); Iteration 2
DEBUG:root:Pixel at position 0,0: (32, 96, 93)
INFO:root:Setting activity: In main menu
DEBUG:rpc:sending {'cmd': 'SET_ACTIVITY', 'args': {'pid': 3636, 'activity': {'details': 'In main menu', 'timestamps': {'start': 1685012282}, 'assets': {'large_image': 'wow-icon'}}}, 'nonce': '4c605391-e5a6-4dd5-a788-e1735b6540de'}
DEBUG:root:Window rectangle: (0, 0, 1920, 2); Iteration 0
DEBUG:root:Pixel at position 0,0: (30, 20, 17)
DEBUG:root:Window border height: 31
DEBUG:root:Window rectangle: (0, 31, 1920, 33); Iteration 1
DEBUG:root:Pixel at position 0,0: (69, 48, 60)
DEBUG:root:Window rectangle: (8, 31, 1920, 33); Iteration 2
DEBUG:root:Pixel at position 0,0: (32, 96, 93)
INFO:root:Setting activity: In main menu
DEBUG:rpc:sending {'cmd': 'SET_ACTIVITY', 'args': {'pid': 3636, 'activity': {'details': 'In main menu', 'timestamps': {'start': 1685012282}, 'assets': {'large_image': 'wow-icon'}}}, 'nonce': 'ca3a3db7-a4f9-4bb1-813a-626c2e60de8d'}
DEBUG:root:Window rectangle: (0, 0, 1920, 2); Iteration 0
DEBUG:root:Pixel at position 0,0: (145, 115, 147)
DEBUG:root:Window border height: 31
DEBUG:root:Window rectangle: (0, 31, 1920, 33); Iteration 1
DEBUG:root:Pixel at position 0,0: (165, 125, 165)
DEBUG:root:Window rectangle: (8, 31, 1920, 33); Iteration 2
DEBUG:root:Pixel at position 0,0: (32, 96, 93)
INFO:root:Setting activity: In main menu
DEBUG:rpc:sending {'cmd': 'SET_ACTIVITY', 'args': {'pid': 3636, 'activity': {'details': 'In main menu', 'timestamps': {'start': 1685012282}, 'assets': {'large_image': 'wow-icon'}}}, 'nonce': '7680b189-8b23-4292-aee5-0e58290d3950'}
DEBUG:root:Window rectangle: (0, 0, 1920, 2); Iteration 0
DEBUG:root:Pixel at position 0,0: (35, 29, 24)
DEBUG:root:Window border height: 31
DEBUG:root:Window rectangle: (0, 31, 1920, 33); Iteration 1
DEBUG:root:Pixel at position 0,0: (26, 26, 10)
DEBUG:root:Window rectangle: (8, 31, 1920, 33); Iteration 2
DEBUG:root:Pixel at position 0,0: (32, 96, 93)
INFO:root:Setting activity: In main menu
DEBUG:rpc:sending {'cmd': 'SET_ACTIVITY', 'args': {'pid': 3636, 'activity': {'details': 'In main menu', 'timestamps': {'start': 1685012282}, 'assets': {'large_image': 'wow-icon'}}}, 'nonce': '5ac83070-2bc0-4d7d-a059-1dd04c58eea6'}
DEBUG:root:Window rectangle: (0, 0, 1920, 2); Iteration 0
DEBUG:root:Pixel at position 0,0: (35, 34, 20)
DEBUG:root:Window border height: 31
DEBUG:root:Window rectangle: (0, 31, 1920, 33); Iteration 1
DEBUG:root:Pixel at position 0,0: (95, 55, 89)
DEBUG:root:Window rectangle: (8, 31, 1920, 33); Iteration 2
DEBUG:root:Pixel at position 0,0: (32, 96, 93)
INFO:root:Setting activity: In main menu
DEBUG:rpc:sending {'cmd': 'SET_ACTIVITY', 'args': {'pid': 3636, 'activity': {'details': 'In main menu', 'timestamps': {'start': 1685012282}, 'assets': {'large_image': 'wow-icon'}}}, 'nonce': '0a8785de-6c41-4324-ac38-b4bdb71c9575'}
DEBUG:root:Window rectangle: (0, 0, 1920, 2); Iteration 0
DEBUG:root:Pixel at position 0,0: (65, 39, 38)
DEBUG:root:Window border height: 31
DEBUG:root:Window rectangle: (0, 31, 1920, 33); Iteration 1
DEBUG:root:Pixel at position 0,0: (148, 87, 87)
DEBUG:root:Window rectangle: (8, 31, 1920, 33); Iteration 2
DEBUG:root:Pixel at position 0,0: (32, 96, 93)
INFO:root:Setting activity: In main menu
DEBUG:rpc:sending {'cmd': 'SET_ACTIVITY', 'args': {'pid': 3636, 'activity': {'details': 'In main menu', 'timestamps': {'start': 1685012282}, 'assets': {'large_image': 'wow-icon'}}}, 'nonce': '59d4d9ac-6af6-4e43-81e3-37314af9354c'}
INFO:root:WoW no longer exists, terminating...
WARNING:rpc:closing connection
DEBUG:rpc:sending {}
`

Sadly it still doesn't really change the fact it doesn't update my discord status.  apart from in main menu

**Comment by AipNooBest** [comment]
Oddly, the only stable color that python script has found is (32, 96, 93), which I can't find on your screenshot and it doesn't decode into anything. I'll look into it this weekend

**Comment by PentSec** [comment]
Hello, did you find a solution so that the addons can be executed on a wotlk 3.3.5 client? it seems that the IPC is frozen, the /ipc command cannot be executed and in the log I get the same error message. 

INFO:root:Setting activity: In main menu
INFO:root:Setting activity: In main menu
INFO:root:Setting activity: In main menu

btw ur code is so good, I hope I can get it to work in 3.3.5

**Comment by AipNooBest** [comment]
Hello, I haven't found a solution yet. I guess if the addon itself isn't working, you have to change Interface version in IPC.toc to 30300 or mark "ignore outdated extensions". Then don't forget to change some lines in IPC.lua and local.lua, which are commented. If the addon is actually working, there's something wrong with the Python script, and I still don't know what exactly...

Looks like it's better to make a new branch for 3.3.5, because every time there's more and more things to change, and it's much easier to download an alternative branch than change all these things manually ¯\\\_(ツ)\_/¯

**Comment by AipNooBest** [comment]
Good news! I've managed to make some progress and as a bonus *maybe* get rid of black pixels, which were used as temp bad fix and are actually redundant as I came to a new solution. PR soon!
